### ISSUE TITLE
some problems with running this code 

### ISSUE THREAD

**Issue by houuuuuie** [git-disl/scale-fl#1]
hello, @fatih-ilhan 
I follow the setting in your readme file, but I find something very strange.
The command line is as follows,
python main.py --data-root datasets/ --data cifar10 --arch resnet110_4 --use-valid

args:Namespace(KD_T=3, KD_gamma=0, alpha=1, arch='resnet110_4', batch_size=None, client_split_ratios=[0.25, 0.25, 0.25, 0.25], data='cifar10', data_root='datasets/', ee_locs=[], evalmode=None, evaluate_from=None, gpu_idx=None, horizontal_scale_ratios=[1, 2, 3, 4], image_size=(32, 32), num_classes=10, num_clients=100, num_exits=4, num_fed_workers=1, num_rounds=2, print_freq=10, resume=False, sample_rate=0.1, save_path='outputs/resnet110_4_None_cifar10_2023-12-19 16:06:18.909166_100_2_0.1_1', seed=0, splits=['train', 'val', 'test'], start_round=0, track_running_stats=False, use_gpu=1, use_valid=True, vertical_scale_ratios=[0.7, 0.7, 0.75, 1], workers=0)

test scores: Model index 0 * prec@1 15.762 prec@5 60.200
 

The results are far away from 79%
![image](https://github.com/git-disl/scale-fl/assets/48352724/0d4abce1-39f5-4984-85de-40474e63be56)

There is anther  issue: 
![image](https://github.com/git-disl/scale-fl/assets/48352724/b4451d22-117d-4ba7-b946-a640ca07ea56)
No.1 is 14.963% but No.5 is 58.704%. I'm guessing there's something wrong with the ordering.
Thank you for your time and consideration.

Warm regards,
Hou

**Comment by fatih-ilhan** [comment]
Hi, looks like the default number of rounds in args.py is 2. It should have been 400/90 for CIFAR/ImageNet experiments.

**Comment by houuuuuie** [comment]
Hi, fatih-ilhan
Ok, thank you for your reply. I set net number of rounds to 400 , and this problem has been solved. 
Thank you very much!

Warm regards,
Hou

**Comment by houuuuuie** [comment]
Hi, fatih-ilhan
Thank you for your reply. I set the number of rounds to 400 , and this problem has been solved.
Thank you very much!

Warm regards,
Hou
